name: Generate Issue Comment

on:
  #workflow_dispatch:
  #schedule:
    #- cron: '59 23 * * *'

env:
  ISSUE_NUMBER: 32
  FROM_ISSUE_NUMBER: 9

jobs:
  sync:
    name: Generate Issue Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate Issue Comment
        run: |
          source venv/bin/activate
          python generate_issue_comment.py ${{ secrets.G_T }} ${{ github.repository }} --from_issue_number ${{ env.FROM_ISSUE_NUMBER }} --issue_number ${{ env.ISSUE_NUMBER }}
